entities:
  minions:
    miner:
      name: "&cMinion"
      coordinates:
        spawnpoint:
          x: 1
          y: 60
          z: 1
          yaw:
          pitch:
  npcs:
    global:
      appearance:
        texture: "ewogICJ0aW1lc3RhbXAiIDogMTcyNjY4MDkwMjE5OCwKICAicHJvZmlsZUlkIiA6ICJiOWRjZjg1ODAyZmU0NzhjYTQ1YjVjNDFlNjZkMjQ1YSIsCiAgInByb2ZpbGVOYW1lIiA6ICJLYWk1MTIiLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvN2Q4MDczNDg5OTgzYjAyNGEzMmY3YjhiNDkzMTkzY2ZlYzNmY2Y3OGM3NzcxZjU0OWM2NDdhNjM3YTQ0ZjFmNiIKICAgIH0sCiAgICAiQ0FQRSIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvY2Q5ZDgyYWIxN2ZkOTIwMjJkYmQ0YTg2Y2RlNGMzODJhNzU0MGUxMTdmYWU3YjlhMjg1MzY1ODUwNWE4MDYyNSIKICAgIH0KICB9Cn0"
        signature: "q1+UQqB0qsSlREjR7/TzVijw7e+Xay1f5u+WMwHrDLV4oeod6/tNHRyhx+4c51jGAUWXR+0jKCMbRqIy/mcqqOeBTlRjoDDGgYH0v0laDp5MQ5DPQmToydp2m2wglBeBt4CXTSwyZkYbBek60LiFf3z3WGYYuffPDKLyK5owLhGhKvTlxa414d28SlCwjqxaFbqAZ9Z16BbTaZSP0lRQyUqLaV0YBQSUl4m74X/tHawqEqXYdyKdNKDd1Qucr2tP1vtYOO2ZiCExcQuOD1DYzQX3ucrrGRUfm24hVOenGZP0DHTBvqI7jGLjc40IP3JYuKCMVkZgY7S9CkRMdAFJzr056bV6MGSBUaTs46TR25DczJ+pIkv7hOxahVIlVQgCavr3OJVsGfRACR7ILdJctd4DBZHy21qpzPTd2DMnUD+uP8lT9MQEcJ3q3SXgtIAtJQX7umUU6UXS50rgY85DN08NjwsR8owRuCBeyz4zuTZUOfMsyaUkiTbkWuAn+O0QeTrgTjKTYUUMmQ4NOHifJ779Q5CFhlBRua7ogxl+dH0NXNDsj/YlDRRzk7dqIsmwcu/h7RTmkKTazfcslOfmYd/0DT386Qi9jNsNdQ5BbY80fli/fSrn1w9YMwnX/uQvcwZyj/INwV7qc2sGgWOkByPh63UvQYgA9I6gfJ7GYzI="
    list:
      MrDefault:
        attributes:
          type: "general"
        coordinates:
          x: 100
          y: 100
          z: 100
          world: "world"