entities:
  minions:
    miner:
      name: "&cMinion"
      coordinates:
        spawnpoint:
          x: 1
          y: 60
          z: 1
          yaw:
          pitch:
  npcs:
    jhonny:
      appearance:
        texture: ""
        signature: ""
      attributes:
        type: