entities:
  minions:
    miner:
      name: "&cMinion"
      coordinates:
        spawnpoint:
          x: 1
          y: 60
          z: 1
          yaw:
          pitch:
  npcs:
    global:
      appearance:
        texture: "ewogICJ0aW1lc3RhbXAiIDogMTcyNjkyNjE0OTM0NywKICAicHJvZmlsZUlkIiA6ICI4Nzg3NWQ0NjYwMGM0NThhYWNlMmM3MWJhZGUyYmVjZiIsCiAgInByb2ZpbGVOYW1lIiA6ICJNM05UNEw1MTUwIiwKICAic2lnbmF0dXJlUmVxdWlyZWQiIDogdHJ1ZSwKICAidGV4dHVyZXMiIDogewogICAgIlNLSU4iIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzQzZTA1NjhlZmU4ZmZkMzA3YTVjYjdmZjBhMzhmMDIxZGJkMTcyNjA0ODYwY2RiMmMyNjMxM2NkYmJiMGM1ZmYiCiAgICB9CiAgfQp9"
        signature: "SIvmsQ/Yrt0zMSKiLz0jACNYn6lu7MkhgEcggWGHjUfQDqVRJ9z8b+xQmq+rgYzCksgNq7A4YV7Pi1CDZbtqS04on3GVabrFK7WdYGycN7OuBg2rWqemxNskuOqPsIlmLz1AEZHFQ/K3R4dNPeFnoI9pwNWmUoP+3o5Vhsv6I/WJKdsaJah6GL3P81W3xkf0e4Yl5wbOWu77pnNaSfO5Ku6d0VXmd8AVEhxwVHbXCEMjNMiII9RPigtfZzREwgUUsjVuWZfOIZztSXw5lAdCxVTUcxC27SFcHzSNL3OGOnzltOM7LipWJ+WDvcpOn6n6mbSFnZmed+Gn8SWwsNSSS/PPVTlEdRH/YzoSEvoPjxdeiLMbt25f+kRD5hgVxf9OE2MzwvXcU1KRNCrWs3Ck5NZqszPtQ7iUNnVM7u/DXqZP5r9/EkS08V4ohtzXCF6V1Z4avYmc8NVnGeQVYJWYKuS59kM/8r/vBJTXF5m0cfsBd2EjsyoTxqs19GLaIfUH3tN7zmbS3HIX9OVzGN+k3JP5pSP94O9Q/pUDKZWPKgHku2Qle9WyxbRUJJwbH93iFu/ZARFbBE4WYZNedbsUaQatv+8pSoaWWUevtbonDU/vqipnMTrIqyiyCI8tYgT079rVtiVBi+HesrvmvgTnkGW56yHrZRLVlZeHfVU+3qE="
    list:
      MrDefault:
        coordinates:
          x: 1
          y: 1
          z: 1
          world: world
        attributes:
          type: general