entities:
  minions:
    miner:
      name: "&cMinion"
      coordinates:
        spawnpoint:
          x: 1
          y: 60
          z: 1
          yaw:
          pitch:
  npcs:
    global:
      appearance:
        texture: "ewogICJ0aW1lc3RhbXAiIDogMTcyNjg0Mjg3NDk1MCwKICAicHJvZmlsZUlkIiA6ICI1ZGRhYTM0MWU0ZDg0ZDM0YTU0ZmMxZGNmZjgyM2RjMiIsCiAgInByb2ZpbGVOYW1lIiA6ICJOb3RjaF81IiwKICAic2lnbmF0dXJlUmVxdWlyZWQiIDogdHJ1ZSwKICAidGV4dHVyZXMiIDogewogICAgIlNLSU4iIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzNiOGEwZmYwNGYxYzQ3YmE0MzJiZDc3Nzc3NGFkZTY5ZjQ0MzUwOWRhODU0MTM5MDk1M2VjMWY5MTA2Zjc4M2YiCiAgICB9CiAgfQp9"
        signature: "U6iMJGMIdgRhe2qC/mnmQH7lX2LpCTPZgoEy2s94nG8gjcBILWNePBeoQLQvHPdog0elAvKFA3roM4APfXIhILUzZ6OiCQLNjc0P7Sf2NFMLD/QX+2K1v3Qx8Od3Ak1N+fj+Jbp7ZiAWQCy588GIqoCejsXP84ujkWATR6v6klwg6BOAYJrOOzYpPXyWKq7Et8ynNH/nsh7MyKdGBhQr+FZ0IaMJ4zL/yxXvSCHz7t5Rv+5PjBwlsTjlxfVSV2xxc57yJyR5hvoOlwvef8hR3/nUZ2EV8ZAbJCUhyIx0sKtQ5gSDrrzmlvR0oCNhQzVVrPLJf75SHmZi9aBKhrVLkzt6b6E9DFGwCC2A9anIZ04X2i8U1cY71QROUmuOwZ9xlASDhlbcHZiaRyvqfPDL0+cGWiXulKGcD4fh6CPQ2M0+gaTNYjpxiBGygHBOb3KRiCq4xpZK6LRblWiPUcop+rwBHcVGSD5Qhe/WHrCuZclb1UyY8JByJn5CSZpTQ0bNA6YAwcQ/b20aC1fr2qCnie/9/aKSQx17zIloMzfxmsUBoKwS3NZ48LPWbX1NxInW4c7SDysrLRircF496IadXJRaVIMi0fkoj4vmNJVKVXEQNNx4FLr7rEMwGQeZ9qrJ0Z+ZR0mC4uGLLthgjh1S7Rdm56hQOeJS+ERGn7xk2mE="
    list: